name: Helm Repo Index

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ github.token }}

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Create Helm repo index
      run: helm repo index . --url https://charts.wenisch.tech

    - name: Commit and push changes
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add index.yaml
        git diff --cached --quiet && exit 0
        git commit -m "Update Helm repo index"
        git push origin main

    - name: Upload to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        exclude: |
          .git*
          .git/
          .git/**
          .github/
